# Generated by Django 5.1.3 on 2025-01-02 20:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalClan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_tag', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_tag', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClanWarInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.CharField(default='N/A', max_length=50)),
                ('war_info', models.JSONField(default=list)),
                ('point_fetched', models.CharField(default='+4', max_length=50)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='war_information', to='main.globalclan')),
            ],
        ),
        migrations.CreateModel(
            name='ClanMonthlyDataWar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_wars', models.FloatField(default=0.0)),
                ('total_players', models.FloatField(default=0.0)),
                ('total_stars', models.FloatField(default=0.0)),
                ('total_destruction', models.FloatField(default=0.0)),
                ('average_war_size', models.FloatField(default=0.0)),
                ('average_total_stars', models.FloatField(default=0.0)),
                ('average_stars_per_player', models.FloatField(default=0.0)),
                ('average_total_destruction', models.FloatField(default=0.0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('percent_attacks_completed', models.FloatField(default=0.0)),
                ('month_year', models.DateField(default=datetime.date.today)),
                ('current_time', models.CharField(default='N/A', max_length=50)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_data_war', to='main.globalclan')),
            ],
        ),
        migrations.CreateModel(
            name='ClanMonthlyDataGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=list)),
                ('month_year', models.DateField(default=datetime.date.today)),
                ('day_fetched', models.DateField(default=datetime.date.today)),
                ('time_fetched', models.TimeField(default=datetime.time(9, 0))),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_data_general', to='main.globalclan')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=list)),
                ('month_year', models.DateField(default=datetime.date.today)),
                ('time_fetched', models.TimeField(default=datetime.time(9, 0))),
                ('day_fetched', models.DateField(default=datetime.date.today)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_data', to='main.globalplayer')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMonthlyDataWar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_wars', models.IntegerField()),
                ('num_attacks', models.IntegerField()),
                ('num_missed_attacks', models.IntegerField()),
                ('total_stars', models.IntegerField()),
                ('total_destruction', models.IntegerField()),
                ('average_total_stars', models.FloatField()),
                ('average_total_destruction', models.FloatField(default=0)),
                ('clan_name', models.CharField(default='', max_length=50)),
                ('clan_tag', models.CharField(default='', max_length=20)),
                ('month_year', models.DateField(default=datetime.date.today)),
                ('current_time', models.CharField(default='N/A', max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_data_war', to='main.globalplayer')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerWarInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField()),
                ('clan_name', models.CharField(max_length=50)),
                ('clan_tag', models.CharField(max_length=20)),
                ('roster_number', models.IntegerField()),
                ('num_attacks', models.IntegerField()),
                ('num_missed_attacks', models.IntegerField(default=0)),
                ('attack_1_stars', models.IntegerField()),
                ('attack_1_destruction', models.IntegerField()),
                ('attack_2_stars', models.IntegerField()),
                ('attack_2_destruction', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='war_information', to='main.globalplayer')),
            ],
        ),
        migrations.CreateModel(
            name='SavedClan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_tag', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_clans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_tag', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
