# Generated by Django 5.1.3 on 2025-01-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CWLGlobalClan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_tag', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
