# Generated by Django 5.1.3 on 2025-01-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cwlglobalclan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CWLGroupData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_data', models.JSONField(default=list)),
            ],
        ),
    ]
