# Generated by Django 5.1.3 on 2025-01-11 20:24

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cwlgroupdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanCWLInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(default='Nth')),
                ('all_clan_placement', models.JSONField(default=list)),
                ('each_war_data', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
                ('member_data', models.JSONField(default=list)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cwl_information', to='main.globalclan')),
            ],
        ),
    ]
