# Generated by Django 5.1.3 on 2025-01-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_clancwlinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clancwlinformation',
            name='percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='clancwlinformation',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clancwlinformation',
            name='placement',
            field=models.IntegerField(default=0),
        ),
    ]
