# Generated by Django 5.1.3 on 2025-01-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_clancwlinformation_percent_clancwlinformation_stars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clancwlinformation',
            name='league',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='clancwlinformation',
            name='month_year',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='cwlgroupdata',
            name='league',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='cwlgroupdata',
            name='month_year',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
