# Generated by Django 5.1.3 on 2025-01-20 19:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_clancwlinformation_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmonthlydatawar',
            name='num_draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clanmonthlydatawar',
            name='num_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clanmonthlydatawar',
            name='num_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClanLastFiveWars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_wins', models.IntegerField(default=0)),
                ('num_losses', models.IntegerField(default=0)),
                ('num_draws', models.IntegerField(default=0)),
                ('num_wars', models.FloatField(default=0.0)),
                ('total_players', models.FloatField(default=0.0)),
                ('total_stars', models.FloatField(default=0.0)),
                ('total_destruction', models.FloatField(default=0.0)),
                ('average_war_size', models.FloatField(default=0.0)),
                ('average_total_stars', models.FloatField(default=0.0)),
                ('average_stars_per_player', models.FloatField(default=0.0)),
                ('average_total_destruction', models.FloatField(default=0.0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('percent_attacks_completed', models.FloatField(default=0.0)),
                ('month_year', models.DateField(default=datetime.date.today)),
                ('current_time', models.CharField(default='N/A', max_length=50)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_five_wars', to='main.globalclan')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLastFiveWars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_wars', models.IntegerField()),
                ('num_attacks', models.IntegerField()),
                ('num_missed_attacks', models.IntegerField()),
                ('total_stars', models.IntegerField()),
                ('total_destruction', models.IntegerField()),
                ('average_total_stars', models.FloatField()),
                ('average_total_destruction', models.FloatField(default=0)),
                ('clan_name', models.CharField(default='', max_length=50)),
                ('clan_tag', models.CharField(default='', max_length=20)),
                ('month_year', models.DateField(default=datetime.date.today)),
                ('current_time', models.CharField(default='N/A', max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_five_wars', to='main.globalplayer')),
            ],
        ),
    ]
